Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "portable"

  config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # add synced folder - set owner to vagrant:vagrant, create folder on host if it doesn't exist
  config.vm.synced_folder "code/", "/home/vagrant/code", owner: "vagrant", group: "vagrant", mount_options: ["dmode=775,fmode=664"], create: true

  config.vm.provision "shell", path: "https://raw.github.com/martyla/vagrant/master/scripts/bootstrap.sh"
  config.vm.provision "shell", path: "https://raw.github.com/martyla/vagrant/master/scripts/dotfiles.sh"
  config.vm.provision "shell", path: "https://raw.github.com/martyla/vagrant/master/scripts/node.sh"
end
