Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "glasshat"

  config.ssh.forward_agent = true

  # glasshat app ports
  config.vm.network "forwarded_port", host: 3333, guest: 3333
  config.vm.network "forwarded_port", host: 9876, guest: 9876

  config.vm.provider :virtualbox do |vb|
    vb.name = "glasshat"
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # add synced folder - set owner to vagrant:vagrant, create folder on host if it doesn't exist
  config.vm.synced_folder "shared/", "/home/vagrant/shared", owner: "vagrant", group: "vagrant", mount_options: ["dmode=775,fmode=664"], create: true

  config.vm.provision "shell", path: "https://raw.github.com/martyla/vagrant/master/scripts/bootstrap.sh"
  config.vm.provision "shell", path: "https://raw.github.com/martyla/vagrant/master/scripts/dotfiles.sh"
  config.vm.provision "shell", path: "https://raw.github.com/martyla/vagrant/master/scripts/node.sh"
  config.vm.provision "shell", path: "https://raw.github.com/martyla/vagrant/master/scripts/glasshat.sh"
end
